// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq1WtBRBIOhMI6mNQ5L4v9MfEXX-UpXcI',
    appId: '1:444593454318:android:96b62a9c34ac8b877587ff',
    messagingSenderId: '444593454318',
    projectId: 'vdlapp-6f149',
    storageBucket: 'vdlapp-6f149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYS7N_Om_DUgtBPfSjdsJrc2UudDCZ8Vs',
    appId: '1:444593454318:ios:9f485829164444187587ff',
    messagingSenderId: '444593454318',
    projectId: 'vdlapp-6f149',
    storageBucket: 'vdlapp-6f149.appspot.com',
    iosClientId:
        '444593454318-6ishov9d4ipe4rc43j2vls19laon748j.apps.googleusercontent.com',
    iosBundleId: 'com.zackanton.vdl',
  );
}
